/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-TRIGGERED-RESPONSE"
 * 	found in "../supl-triggered-response.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_BatchRepConditions_H_
#define	_BatchRepConditions_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BatchRepConditions_PR {
	BatchRepConditions_PR_NOTHING,	/* No components present */
	BatchRepConditions_PR_num_interval,
	BatchRepConditions_PR_num_minutes,
	BatchRepConditions_PR_endofsession,
	/* Extensions may appear below */
	
} BatchRepConditions_PR;

/* BatchRepConditions */
typedef struct BatchRepConditions {
	BatchRepConditions_PR present;
	union BatchRepConditions_u {
		long	 num_interval;
		long	 num_minutes;
		NULL_t	 endofsession;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BatchRepConditions_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BatchRepConditions;

#ifdef __cplusplus
}
#endif

#endif	/* _BatchRepConditions_H_ */
#include <asn_internal.h>
