/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_Coordinate_H_
#define	_Coordinate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Coordinate__latitudeSign {
	Coordinate__latitudeSign_north	= 0,
	Coordinate__latitudeSign_south	= 1
} e_Coordinate__latitudeSign;

/* Coordinate */
typedef struct Coordinate {
	long	 latitudeSign;
	long	 latitude;
	long	 longitude;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Coordinate_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_latitudeSign_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Coordinate;

#ifdef __cplusplus
}
#endif

#endif	/* _Coordinate_H_ */
#include <asn_internal.h>
