/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_EllipticalArea_H_
#define	_EllipticalArea_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Coordinate.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EllipticalArea */
typedef struct EllipticalArea {
	Coordinate_t	 coordinate;
	long	 semiMajor;
	long	*semiMajor_min	/* OPTIONAL */;
	long	*semiMajor_max	/* OPTIONAL */;
	long	 semiMinor;
	long	*semiMinor_min	/* OPTIONAL */;
	long	*semiMinor_max	/* OPTIONAL */;
	long	 angle;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EllipticalArea_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EllipticalArea;

#ifdef __cplusplus
}
#endif

#endif	/* _EllipticalArea_H_ */
#include <asn_internal.h>
