/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-TRIGGERED-START"
 * 	found in "../supl-triggered-start.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_GeoAreaMappingList_H_
#define	_GeoAreaMappingList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GeoAreaIndex.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GeoAreaMappingList */
typedef struct GeoAreaMappingList {
	A_SEQUENCE_OF(GeoAreaIndex_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeoAreaMappingList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeoAreaMappingList;

#ifdef __cplusplus
}
#endif

#endif	/* _GeoAreaMappingList_H_ */
#include <asn_internal.h>
