/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Version-2-message-extensions"
 * 	found in "../ulp-version2-message-extensions.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_HistoricReporting_H_
#define	_HistoricReporting_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AllowedReportingType.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReportingCriteria;

/* HistoricReporting */
typedef struct HistoricReporting {
	AllowedReportingType_t	 allowedReportingType;
	struct ReportingCriteria	*reportingCriteria	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HistoricReporting_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HistoricReporting;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReportingCriteria.h"

#endif	/* _HistoricReporting_H_ */
#include <asn_internal.h>
