/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "LocationIdData.h"

static asn_TYPE_member_t asn_MBR_LocationIdData_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct LocationIdData, locationId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocationId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"locationId"
		},
	{ ATF_POINTER, 1, offsetof(struct LocationIdData, relativetimestamp),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RelativeTime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"relativetimestamp"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct LocationIdData, servingFlag),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"servingFlag"
		},
};
static const int asn_MAP_LocationIdData_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_LocationIdData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LocationIdData_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* locationId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* relativetimestamp */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* servingFlag */
};
static asn_SEQUENCE_specifics_t asn_SPC_LocationIdData_specs_1 = {
	sizeof(struct LocationIdData),
	offsetof(struct LocationIdData, _asn_ctx),
	asn_MAP_LocationIdData_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_LocationIdData_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_LocationIdData = {
	"LocationIdData",
	"LocationIdData",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_LocationIdData_tags_1,
	sizeof(asn_DEF_LocationIdData_tags_1)
		/sizeof(asn_DEF_LocationIdData_tags_1[0]), /* 1 */
	asn_DEF_LocationIdData_tags_1,	/* Same as above */
	sizeof(asn_DEF_LocationIdData_tags_1)
		/sizeof(asn_DEF_LocationIdData_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_LocationIdData_1,
	3,	/* Elements count */
	&asn_SPC_LocationIdData_specs_1	/* Additional specs */
};

