/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_LocationIdData_H_
#define	_LocationIdData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LocationId.h"
#include "RelativeTime.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LocationIdData */
typedef struct LocationIdData {
	LocationId_t	 locationId;
	RelativeTime_t	*relativetimestamp	/* OPTIONAL */;
	BOOLEAN_t	 servingFlag;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LocationIdData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocationIdData;

#ifdef __cplusplus
}
#endif

#endif	/* _LocationIdData_H_ */
#include <asn_internal.h>
