/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_PhysCellId_H_
#define	_PhysCellId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PhysCellId */
typedef long	 PhysCellId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysCellId;
asn_struct_free_f PhysCellId_free;
asn_struct_print_f PhysCellId_print;
asn_constr_check_f PhysCellId_constraint;
ber_type_decoder_f PhysCellId_decode_ber;
der_type_encoder_f PhysCellId_encode_der;
xer_type_decoder_f PhysCellId_decode_xer;
xer_type_encoder_f PhysCellId_encode_xer;
per_type_decoder_f PhysCellId_decode_uper;
per_type_encoder_f PhysCellId_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _PhysCellId_H_ */
#include <asn_internal.h>
