/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-TRIGGERED-RESPONSE"
 * 	found in "../supl-triggered-response.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_RepModee_H_
#define	_RepModee_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RepModee {
	RepModee_realtime	= 1,
	RepModee_quasirealtime	= 2,
	RepModee_batch	= 3
	/*
	 * Enumeration is extensible
	 */
} e_RepModee;

/* RepModee */
typedef long	 RepModee_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RepModee;
asn_struct_free_f RepModee_free;
asn_struct_print_f RepModee_print;
asn_constr_check_f RepModee_constraint;
ber_type_decoder_f RepModee_decode_ber;
der_type_encoder_f RepModee_encode_der;
xer_type_decoder_f RepModee_decode_xer;
xer_type_encoder_f RepModee_encode_xer;
per_type_decoder_f RepModee_decode_uper;
per_type_encoder_f RepModee_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RepModee_H_ */
#include <asn_internal.h>
