/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_ReportedLocation_H_
#define	_ReportedLocation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LocationEncodingDescriptor.h"
#include "LocationData.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReportedLocation */
typedef struct ReportedLocation {
	LocationEncodingDescriptor_t	 locationEncodingDescriptor;
	LocationData_t	 locationData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportedLocation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportedLocation;

#ifdef __cplusplus
}
#endif

#endif	/* _ReportedLocation_H_ */
#include <asn_internal.h>
