/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-TRIGGERED-RESPONSE"
 * 	found in "../supl-triggered-response.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_ReportingMode_H_
#define	_ReportingMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RepModee.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BatchRepConditions;
struct BatchRepType;

/* ReportingMode */
typedef struct ReportingMode {
	RepModee_t	 repMode;
	struct BatchRepConditions	*batchRepConditions	/* OPTIONAL */;
	struct BatchRepType	*batchRepType	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReportingMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReportingMode;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BatchRepConditions.h"
#include "BatchRepType.h"

#endif	/* _ReportingMode_H_ */
#include <asn_internal.h>
