/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Version-2-parameter-extensions"
 * 	found in "../ulp-version2-parameter-extensions.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_SatellitesListRelatedData_H_
#define	_SatellitesListRelatedData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SatellitesListRelatedData */
typedef struct SatellitesListRelatedData {
	long	 satId;
	long	 iod;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SatellitesListRelatedData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SatellitesListRelatedData;

#ifdef __cplusplus
}
#endif

#endif	/* _SatellitesListRelatedData_H_ */
#include <asn_internal.h>
