/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Version-2-parameter-extensions"
 * 	found in "../ulp-version2-parameter-extensions.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_ServiceCapabilities_H_
#define	_ServiceCapabilities_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServicesSupported.h"
#include "SessionCapabilities.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ReportingCap;
struct EventTriggerCapabilities;

/* ServiceCapabilities */
typedef struct ServiceCapabilities {
	ServicesSupported_t	 servicesSupported;
	struct ReportingCap	*reportingCapabilities	/* OPTIONAL */;
	struct EventTriggerCapabilities	*eventTriggerCapabilities	/* OPTIONAL */;
	SessionCapabilities_t	 sessionCapabilities;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ServiceCapabilities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ServiceCapabilities;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReportingCap.h"
#include "EventTriggerCapabilities.h"

#endif	/* _ServiceCapabilities_H_ */
#include <asn_internal.h>
