/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-AUTH-REQ"
 * 	found in "../supl-auth-req.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_SUPLAUTHREQ_H_
#define	_SUPLAUTHREQ_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Ver.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SETCapabilities;

/* SUPLAUTHREQ */
typedef struct SUPLAUTHREQ {
	Ver_t	*ver	/* OPTIONAL */;
	struct SETCapabilities	*sETCapabilities	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SUPLAUTHREQ_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SUPLAUTHREQ;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SETCapabilities.h"

#endif	/* _SUPLAUTHREQ_H_ */
#include <asn_internal.h>
