/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-INIT"
 * 	found in "../supl-init.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "SUPLINIT.h"

static asn_TYPE_member_t asn_MBR_SUPLINIT_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SUPLINIT, posMethod),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PosMethod,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"posMethod"
		},
	{ ATF_POINTER, 3, offsetof(struct SUPLINIT, notification),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Notification,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"notification"
		},
	{ ATF_POINTER, 2, offsetof(struct SUPLINIT, sLPAddress),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SLPAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sLPAddress"
		},
	{ ATF_POINTER, 1, offsetof(struct SUPLINIT, qoP),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoP,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"qoP"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SUPLINIT, sLPMode),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SLPMode,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sLPMode"
		},
	{ ATF_POINTER, 3, offsetof(struct SUPLINIT, mAC),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MAC,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mAC"
		},
	{ ATF_POINTER, 2, offsetof(struct SUPLINIT, keyIdentity),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_KeyIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"keyIdentity"
		},
	{ ATF_POINTER, 1, offsetof(struct SUPLINIT, ver2_SUPL_INIT_extension),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ver2_SUPL_INIT_extension,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ver2-SUPL-INIT-extension"
		},
};
static const int asn_MAP_SUPLINIT_oms_1[] = { 1, 2, 3, 5, 6, 7 };
static const ber_tlv_tag_t asn_DEF_SUPLINIT_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SUPLINIT_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* posMethod */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* notification */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sLPAddress */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* qoP */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* sLPMode */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* mAC */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* keyIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* ver2-SUPL-INIT-extension */
};
static asn_SEQUENCE_specifics_t asn_SPC_SUPLINIT_specs_1 = {
	sizeof(struct SUPLINIT),
	offsetof(struct SUPLINIT, _asn_ctx),
	asn_MAP_SUPLINIT_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_SUPLINIT_oms_1,	/* Optional members */
	5, 1,	/* Root/Additions */
	6,	/* Start extensions */
	9	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_SUPLINIT = {
	"SUPLINIT",
	"SUPLINIT",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SUPLINIT_tags_1,
	sizeof(asn_DEF_SUPLINIT_tags_1)
		/sizeof(asn_DEF_SUPLINIT_tags_1[0]), /* 1 */
	asn_DEF_SUPLINIT_tags_1,	/* Same as above */
	sizeof(asn_DEF_SUPLINIT_tags_1)
		/sizeof(asn_DEF_SUPLINIT_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SUPLINIT_1,
	8,	/* Elements count */
	&asn_SPC_SUPLINIT_specs_1	/* Additional specs */
};

