/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_SupportedWLANApsList_H_
#define	_SupportedWLANApsList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SupportedWLANApsChannel11a;
struct SupportedWLANApsChannel11bg;
struct SupportedWLANApData;

/* SupportedWLANApsList */
typedef struct SupportedWLANApsList {
	struct SupportedWLANApsList__supportedWLANApDataList {
		A_SEQUENCE_OF(struct SupportedWLANApData) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} supportedWLANApDataList;
	struct SupportedWLANApsChannel11a	*supportedWLANapsChannel11a	/* OPTIONAL */;
	struct SupportedWLANApsChannel11bg	*supportedWLANapsChannel11bg	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedWLANApsList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupportedWLANApsList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SupportedWLANApsChannel11a.h"
#include "SupportedWLANApsChannel11bg.h"
#include "SupportedWLANApData.h"

#endif	/* _SupportedWLANApsList_H_ */
#include <asn_internal.h>
