/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_SupportedNetworkInformation_H_
#define	_SupportedNetworkInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SupportedWLANInfo;
struct SupportedWLANApsList;
struct SupportedWCDMAInfo;

/* SupportedNetworkInformation */
typedef struct SupportedNetworkInformation {
	BOOLEAN_t	 wLAN;
	struct SupportedWLANInfo	*supportedWLANInfo	/* OPTIONAL */;
	struct SupportedWLANApsList	*supportedWLANApsList	/* OPTIONAL */;
	BOOLEAN_t	 gSM;
	BOOLEAN_t	 wCDMA;
	struct SupportedWCDMAInfo	*supportedWCDMAInfo	/* OPTIONAL */;
	BOOLEAN_t	 cDMA;
	BOOLEAN_t	 hRDP;
	BOOLEAN_t	 uMB;
	BOOLEAN_t	 lTE;
	BOOLEAN_t	 wIMAX;
	BOOLEAN_t	 historic;
	BOOLEAN_t	 nonServing;
	BOOLEAN_t	 uTRANGPSReferenceTime;
	BOOLEAN_t	 uTRANGANSSReferenceTime;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedNetworkInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupportedNetworkInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SupportedWLANInfo.h"
#include "SupportedWLANApsList.h"
#include "SupportedWCDMAInfo.h"

#endif	/* _SupportedNetworkInformation_H_ */
#include <asn_internal.h>
