/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Version-2-parameter-extensions"
 * 	found in "../ulp-version2-parameter-extensions.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_Supported3GPP2PosProtocolVersion_H_
#define	_Supported3GPP2PosProtocolVersion_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Supported3GPP2PosProtocolVersion */
typedef struct Supported3GPP2PosProtocolVersion {
	BIT_STRING_t	 revisionNumber;
	long	 pointReleaseNumber;
	long	 internalEditLevel;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Supported3GPP2PosProtocolVersion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Supported3GPP2PosProtocolVersion;

#ifdef __cplusplus
}
#endif

#endif	/* _Supported3GPP2PosProtocolVersion_H_ */
#include <asn_internal.h>
