/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_SupportedWLANApData_H_
#define	_SupportedWLANApData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SupportedWLANApData__apDevType {
	SupportedWLANApData__apDevType_wlan802_11a	= 0,
	SupportedWLANApData__apDevType_wlan802_11b	= 1,
	SupportedWLANApData__apDevType_wlan802_11g	= 2
	/*
	 * Enumeration is extensible
	 */
} e_SupportedWLANApData__apDevType;

/* SupportedWLANApData */
typedef struct SupportedWLANApData {
	BIT_STRING_t	 apMACAddress;
	long	 apDevType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedWLANApData_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_apDevType_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SupportedWLANApData;

#ifdef __cplusplus
}
#endif

#endif	/* _SupportedWLANApData_H_ */
#include <asn_internal.h>
