/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Components"
 * 	found in "../ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_TimingAdvance_H_
#define	_TimingAdvance_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "TAResolution.h"
#include "ChipRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimingAdvance */
typedef struct TimingAdvance {
	long	 tA;
	TAResolution_t	*tAResolution	/* OPTIONAL */;
	ChipRate_t	*chipRate	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TimingAdvance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TimingAdvance;

#ifdef __cplusplus
}
#endif

#endif	/* _TimingAdvance_H_ */
#include <asn_internal.h>
