/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-TRIGGERED-START"
 * 	found in "../supl-triggered-start.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_UMBAreaId_H_
#define	_UMBAreaId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UMBAreaId */
typedef struct UMBAreaId {
	long	*refMCC	/* OPTIONAL */;
	long	*refMNC	/* OPTIONAL */;
	BIT_STRING_t	*refSECTORID	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UMBAreaId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UMBAreaId;

#ifdef __cplusplus
}
#endif

#endif	/* _UMBAreaId_H_ */
#include <asn_internal.h>
