/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_UTRAN_GPSReferenceTimeAssistance_H_
#define	_UTRAN_GPSReferenceTimeAssistance_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UTRAN-GPSReferenceTime.h"
#include <NativeInteger.h>
#include "UTRANGPSDriftRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UTRAN-GPSReferenceTimeAssistance */
typedef struct UTRAN_GPSReferenceTimeAssistance {
	UTRAN_GPSReferenceTime_t	 utran_GPSReferenceTime;
	long	*gpsReferenceTimeUncertainty	/* OPTIONAL */;
	UTRANGPSDriftRate_t	*utranGPSDriftRate	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UTRAN_GPSReferenceTimeAssistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UTRAN_GPSReferenceTimeAssistance;

#ifdef __cplusplus
}
#endif

#endif	/* _UTRAN_GPSReferenceTimeAssistance_H_ */
#include <asn_internal.h>
