/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ver2-ulp-components.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "UTRANGPSDriftRate.h"

int
UTRANGPSDriftRate_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
UTRANGPSDriftRate_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

void
UTRANGPSDriftRate_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	UTRANGPSDriftRate_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
UTRANGPSDriftRate_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	UTRANGPSDriftRate_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
UTRANGPSDriftRate_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	UTRANGPSDriftRate_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
UTRANGPSDriftRate_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	UTRANGPSDriftRate_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
UTRANGPSDriftRate_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	UTRANGPSDriftRate_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
UTRANGPSDriftRate_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	UTRANGPSDriftRate_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

asn_dec_rval_t
UTRANGPSDriftRate_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	UTRANGPSDriftRate_1_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

asn_enc_rval_t
UTRANGPSDriftRate_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	UTRANGPSDriftRate_1_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_UTRANGPSDriftRate_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  14 }	/* (0..14) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_UTRANGPSDriftRate_value2enum_1[] = {
	{ 0,	15,	"utran-GPSDrift0" },
	{ 1,	15,	"utran-GPSDrift1" },
	{ 2,	15,	"utran-GPSDrift2" },
	{ 3,	15,	"utran-GPSDrift5" },
	{ 4,	16,	"utran-GPSDrift10" },
	{ 5,	16,	"utran-GPSDrift15" },
	{ 6,	16,	"utran-GPSDrift25" },
	{ 7,	16,	"utran-GPSDrift50" },
	{ 8,	16,	"utran-GPSDrift-1" },
	{ 9,	16,	"utran-GPSDrift-2" },
	{ 10,	16,	"utran-GPSDrift-5" },
	{ 11,	17,	"utran-GPSDrift-10" },
	{ 12,	17,	"utran-GPSDrift-15" },
	{ 13,	17,	"utran-GPSDrift-25" },
	{ 14,	17,	"utran-GPSDrift-50" }
};
static const unsigned int asn_MAP_UTRANGPSDriftRate_enum2value_1[] = {
	8,	/* utran-GPSDrift-1(8) */
	11,	/* utran-GPSDrift-10(11) */
	12,	/* utran-GPSDrift-15(12) */
	9,	/* utran-GPSDrift-2(9) */
	13,	/* utran-GPSDrift-25(13) */
	10,	/* utran-GPSDrift-5(10) */
	14,	/* utran-GPSDrift-50(14) */
	0,	/* utran-GPSDrift0(0) */
	1,	/* utran-GPSDrift1(1) */
	4,	/* utran-GPSDrift10(4) */
	5,	/* utran-GPSDrift15(5) */
	2,	/* utran-GPSDrift2(2) */
	6,	/* utran-GPSDrift25(6) */
	3,	/* utran-GPSDrift5(3) */
	7	/* utran-GPSDrift50(7) */
};
static const asn_INTEGER_specifics_t asn_SPC_UTRANGPSDriftRate_specs_1 = {
	asn_MAP_UTRANGPSDriftRate_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_UTRANGPSDriftRate_enum2value_1,	/* N => "tag"; sorted by N */
	15,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_UTRANGPSDriftRate_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_UTRANGPSDriftRate = {
	"UTRANGPSDriftRate",
	"UTRANGPSDriftRate",
	UTRANGPSDriftRate_free,
	UTRANGPSDriftRate_print,
	UTRANGPSDriftRate_constraint,
	UTRANGPSDriftRate_decode_ber,
	UTRANGPSDriftRate_encode_der,
	UTRANGPSDriftRate_decode_xer,
	UTRANGPSDriftRate_encode_xer,
	UTRANGPSDriftRate_decode_uper,
	UTRANGPSDriftRate_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_UTRANGPSDriftRate_tags_1,
	sizeof(asn_DEF_UTRANGPSDriftRate_tags_1)
		/sizeof(asn_DEF_UTRANGPSDriftRate_tags_1[0]), /* 1 */
	asn_DEF_UTRANGPSDriftRate_tags_1,	/* Same as above */
	sizeof(asn_DEF_UTRANGPSDriftRate_tags_1)
		/sizeof(asn_DEF_UTRANGPSDriftRate_tags_1[0]), /* 1 */
	&asn_PER_type_UTRANGPSDriftRate_constr_1,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_UTRANGPSDriftRate_specs_1	/* Additional specs */
};

