/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-TRIGGERED-START"
 * 	found in "../supl-triggered-start.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_Ver2_SUPLTRIGGEREDSTART_H_
#define	_Ver2_SUPLTRIGGEREDSTART_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SETCapabilities.h"
#include "LocationId.h"
#include "Ver.h"
#include "TriggerType.h"
#include "CauseCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct QoP;
struct MultipleLocationIds;
struct ThirdParty;
struct ApplicationID;
struct TriggerParams;
struct Position;
struct ReportingCap;

/* Ver2-SUPLTRIGGEREDSTART */
typedef struct Ver2_SUPLTRIGGEREDSTART {
	SETCapabilities_t	 sETCapabilities;
	LocationId_t	 locationId;
	Ver_t	*ver	/* OPTIONAL */;
	struct QoP	*qoP	/* OPTIONAL */;
	struct MultipleLocationIds	*multipleLocationIds	/* OPTIONAL */;
	struct ThirdParty	*thirdParty	/* OPTIONAL */;
	struct ApplicationID	*applicationID	/* OPTIONAL */;
	TriggerType_t	*triggerType	/* OPTIONAL */;
	struct TriggerParams	*triggerParams	/* OPTIONAL */;
	struct Position	*position	/* OPTIONAL */;
	struct ReportingCap	*reportingCap	/* OPTIONAL */;
	CauseCode_t	*causeCode	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ver2_SUPLTRIGGEREDSTART_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ver2_SUPLTRIGGEREDSTART;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "QoP.h"
#include "MultipleLocationIds.h"
#include "ThirdParty.h"
#include "ApplicationID.h"
#include "TriggerParams.h"
#include "Position.h"
#include "ReportingCap.h"

#endif	/* _Ver2_SUPLTRIGGEREDSTART_H_ */
#include <asn_internal.h>
