/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Version-2-message-extensions"
 * 	found in "../ulp-version2-message-extensions.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_Ver2_SUPL_START_extension_H_
#define	_Ver2_SUPL_START_extension_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MultipleLocationIds;
struct ThirdParty;
struct ApplicationID;
struct Position;

/* Ver2-SUPL-START-extension */
typedef struct Ver2_SUPL_START_extension {
	struct MultipleLocationIds	*multipleLocationIds	/* OPTIONAL */;
	struct ThirdParty	*thirdParty	/* OPTIONAL */;
	struct ApplicationID	*applicationID	/* OPTIONAL */;
	struct Position	*position	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ver2_SUPL_START_extension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ver2_SUPL_START_extension;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MultipleLocationIds.h"
#include "ThirdParty.h"
#include "ApplicationID.h"
#include "Position.h"

#endif	/* _Ver2_SUPL_START_extension_H_ */
#include <asn_internal.h>
