/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-REPORT"
 * 	found in "../supl-report.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "Ver2-SUPLREPORT.h"

static asn_TYPE_member_t asn_MBR_Ver2_SUPLREPORT_1[] = {
	{ ATF_POINTER, 5, offsetof(struct Ver2_SUPLREPORT, sessionList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SessionList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sessionList"
		},
	{ ATF_POINTER, 4, offsetof(struct Ver2_SUPLREPORT, sETCapabilities),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SETCapabilities,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sETCapabilities"
		},
	{ ATF_POINTER, 3, offsetof(struct Ver2_SUPLREPORT, reportDataList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReportDataList,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportDataList"
		},
	{ ATF_POINTER, 2, offsetof(struct Ver2_SUPLREPORT, ver),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ver,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ver"
		},
	{ ATF_POINTER, 1, offsetof(struct Ver2_SUPLREPORT, moreComponents),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"moreComponents"
		},
};
static const int asn_MAP_Ver2_SUPLREPORT_oms_1[] = { 0, 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_Ver2_SUPLREPORT_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Ver2_SUPLREPORT_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sessionList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sETCapabilities */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* reportDataList */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ver */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* moreComponents */
};
static asn_SEQUENCE_specifics_t asn_SPC_Ver2_SUPLREPORT_specs_1 = {
	sizeof(struct Ver2_SUPLREPORT),
	offsetof(struct Ver2_SUPLREPORT, _asn_ctx),
	asn_MAP_Ver2_SUPLREPORT_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_Ver2_SUPLREPORT_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Ver2_SUPLREPORT = {
	"Ver2-SUPLREPORT",
	"Ver2-SUPLREPORT",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Ver2_SUPLREPORT_tags_1,
	sizeof(asn_DEF_Ver2_SUPLREPORT_tags_1)
		/sizeof(asn_DEF_Ver2_SUPLREPORT_tags_1[0]), /* 1 */
	asn_DEF_Ver2_SUPLREPORT_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ver2_SUPLREPORT_tags_1)
		/sizeof(asn_DEF_Ver2_SUPLREPORT_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Ver2_SUPLREPORT_1,
	5,	/* Elements count */
	&asn_SPC_Ver2_SUPLREPORT_specs_1	/* Additional specs */
};

