/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Version-2-message-extensions"
 * 	found in "../ulp-version2-message-extensions.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#include "Ver2-SUPL-RESPONSE-extension.h"

static asn_TYPE_member_t asn_MBR_Ver2_SUPL_RESPONSE_extension_1[] = {
	{ ATF_POINTER, 6, offsetof(struct Ver2_SUPL_RESPONSE_extension, supportedNetworkInformation),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SupportedNetworkInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"supportedNetworkInformation"
		},
	{ ATF_POINTER, 5, offsetof(struct Ver2_SUPL_RESPONSE_extension, sPCSETKey),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPCSETKey,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sPCSETKey"
		},
	{ ATF_POINTER, 4, offsetof(struct Ver2_SUPL_RESPONSE_extension, sPCTID),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPCTID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sPCTID"
		},
	{ ATF_POINTER, 3, offsetof(struct Ver2_SUPL_RESPONSE_extension, sPCSETKeylifetime),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SPCSETKeylifetime,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"sPCSETKeylifetime"
		},
	{ ATF_POINTER, 2, offsetof(struct Ver2_SUPL_RESPONSE_extension, initialApproximateposition),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Position,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"initialApproximateposition"
		},
	{ ATF_POINTER, 1, offsetof(struct Ver2_SUPL_RESPONSE_extension, gnssPosTechnology),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GNSSPosTechnology,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"gnssPosTechnology"
		},
};
static const int asn_MAP_Ver2_SUPL_RESPONSE_extension_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_Ver2_SUPL_RESPONSE_extension_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Ver2_SUPL_RESPONSE_extension_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedNetworkInformation */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sPCSETKey */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sPCTID */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sPCSETKeylifetime */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* initialApproximateposition */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* gnssPosTechnology */
};
static asn_SEQUENCE_specifics_t asn_SPC_Ver2_SUPL_RESPONSE_extension_specs_1 = {
	sizeof(struct Ver2_SUPL_RESPONSE_extension),
	offsetof(struct Ver2_SUPL_RESPONSE_extension, _asn_ctx),
	asn_MAP_Ver2_SUPL_RESPONSE_extension_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_Ver2_SUPL_RESPONSE_extension_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Ver2_SUPL_RESPONSE_extension = {
	"Ver2-SUPL-RESPONSE-extension",
	"Ver2-SUPL-RESPONSE-extension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Ver2_SUPL_RESPONSE_extension_tags_1,
	sizeof(asn_DEF_Ver2_SUPL_RESPONSE_extension_tags_1)
		/sizeof(asn_DEF_Ver2_SUPL_RESPONSE_extension_tags_1[0]), /* 1 */
	asn_DEF_Ver2_SUPL_RESPONSE_extension_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ver2_SUPL_RESPONSE_extension_tags_1)
		/sizeof(asn_DEF_Ver2_SUPL_RESPONSE_extension_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Ver2_SUPL_RESPONSE_extension_1,
	6,	/* Elements count */
	&asn_SPC_Ver2_SUPL_RESPONSE_extension_specs_1	/* Additional specs */
};

