/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-NOTIFY-RESPONSE"
 * 	found in "../supl-notify-response.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_Ver2_SUPLNOTIFYRESPONSE_H_
#define	_Ver2_SUPLNOTIFYRESPONSE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NotificationResponse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ver2-SUPLNOTIFYRESPONSE */
typedef struct Ver2_SUPLNOTIFYRESPONSE {
	NotificationResponse_t	*notificationResponse	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ver2_SUPLNOTIFYRESPONSE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ver2_SUPLNOTIFYRESPONSE;

#ifdef __cplusplus
}
#endif

#endif	/* _Ver2_SUPLNOTIFYRESPONSE_H_ */
#include <asn_internal.h>
