/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-TRIGGERED-RESPONSE"
 * 	found in "../supl-triggered-response.asn"
 * 	`asn1c -fcompound-names -gen-PER`
 */

#ifndef	_Ver2_SUPLTRIGGEREDRESPONSE_H_
#define	_Ver2_SUPLTRIGGEREDRESPONSE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PosMethod.h"
#include "SPCSETKey.h"
#include "SPCSETKeylifetime.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TriggerParams;
struct SLPAddress;
struct SupportedNetworkInformation;
struct ReportingMode;
struct SPCTID;
struct GNSSPosTechnology;

/* Ver2-SUPLTRIGGEREDRESPONSE */
typedef struct Ver2_SUPLTRIGGEREDRESPONSE {
	PosMethod_t	 posMethod;
	struct TriggerParams	*triggerParams	/* OPTIONAL */;
	struct SLPAddress	*sLPAddress	/* OPTIONAL */;
	struct SupportedNetworkInformation	*supportedNetworkInformation	/* OPTIONAL */;
	struct ReportingMode	*reportingMode	/* OPTIONAL */;
	SPCSETKey_t	*sPCSETKey	/* OPTIONAL */;
	struct SPCTID	*sPCTID	/* OPTIONAL */;
	SPCSETKeylifetime_t	*sPCSETKeylifetime	/* OPTIONAL */;
	struct GNSSPosTechnology	*gnssPosTechnology	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ver2_SUPLTRIGGEREDRESPONSE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ver2_SUPLTRIGGEREDRESPONSE;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TriggerParams.h"
#include "SLPAddress.h"
#include "SupportedNetworkInformation.h"
#include "ReportingMode.h"
#include "SPCTID.h"
#include "GNSSPosTechnology.h"

#endif	/* _Ver2_SUPLTRIGGEREDRESPONSE_H_ */
#include <asn_internal.h>
