/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Add_GPS_AssistData_H_
#define	_Add_GPS_AssistData_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Add-GPS-ControlHeader.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Add-GPS-AssistData */
typedef struct Add_GPS_AssistData {
	Add_GPS_ControlHeader_t	 add_GPS_controlHeader;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Add_GPS_AssistData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Add_GPS_AssistData;

#ifdef __cplusplus
}
#endif

#endif	/* _Add_GPS_AssistData_H_ */
#include <asn_internal.h>
