/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Almanac_ECEFsbasAlmanacSet_H_
#define	_Almanac_ECEFsbasAlmanacSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "SVID.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Almanac-ECEFsbasAlmanacSet */
typedef struct Almanac_ECEFsbasAlmanacSet {
	long	 sbasAlmDataID;
	SVID_t	 svID;
	BIT_STRING_t	 sbasAlmHealth;
	long	 sbasAlmXg;
	long	 sbasAlmYg;
	long	 sbasAlmZg;
	long	 sbasAlmXgdot;
	long	 sbasAlmYgDot;
	long	 sbasAlmZgDot;
	long	 sbasAlmTo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Almanac_ECEFsbasAlmanacSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Almanac_ECEFsbasAlmanacSet;

#ifdef __cplusplus
}
#endif

#endif	/* _Almanac_ECEFsbasAlmanacSet_H_ */
#include <asn_internal.h>
