/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_Almanac_GlonassAlmanacSet_H_
#define	_Almanac_GlonassAlmanacSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Almanac-GlonassAlmanacSet */
typedef struct Almanac_GlonassAlmanacSet {
	long	 gloAlmNA;
	long	 gloAlmnA;
	long	 gloAlmHA;
	long	 gloAlmLambdaA;
	long	 gloAlmtlambdaA;
	long	 gloAlmDeltaIa;
	long	 gloAlmDeltaTA;
	long	 gloAlmDeltaTdotA;
	long	 gloAlmEpsilonA;
	long	 gloAlmOmegaA;
	long	 gloAlmTauA;
	long	 gloAlmCA;
	BIT_STRING_t	*gloAlmMA	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Almanac_GlonassAlmanacSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Almanac_GlonassAlmanacSet;

#ifdef __cplusplus
}
#endif

#endif	/* _Almanac_GlonassAlmanacSet_H_ */
#include <asn_internal.h>
