/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#include "BDS-DiffCorrections-r12.h"

static int
memb_dbds_RefTime_r12_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 3599)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_dbds_RefTime_r12_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 12,  12,  0,  3599 }	/* (0..3599) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_BDS_DiffCorrections_r12_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BDS_DiffCorrections_r12, dbds_RefTime_r12),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_dbds_RefTime_r12_constraint_1,
		&asn_PER_memb_dbds_RefTime_r12_constr_2,
		0,
		"dbds-RefTime-r12"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDS_DiffCorrections_r12, bds_SgnTypeList_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BDS_SgnTypeList_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"bds-SgnTypeList-r12"
		},
};
static const ber_tlv_tag_t asn_DEF_BDS_DiffCorrections_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BDS_DiffCorrections_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dbds-RefTime-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* bds-SgnTypeList-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BDS_DiffCorrections_r12_specs_1 = {
	sizeof(struct BDS_DiffCorrections_r12),
	offsetof(struct BDS_DiffCorrections_r12, _asn_ctx),
	asn_MAP_BDS_DiffCorrections_r12_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BDS_DiffCorrections_r12 = {
	"BDS-DiffCorrections-r12",
	"BDS-DiffCorrections-r12",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BDS_DiffCorrections_r12_tags_1,
	sizeof(asn_DEF_BDS_DiffCorrections_r12_tags_1)
		/sizeof(asn_DEF_BDS_DiffCorrections_r12_tags_1[0]), /* 1 */
	asn_DEF_BDS_DiffCorrections_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_BDS_DiffCorrections_r12_tags_1)
		/sizeof(asn_DEF_BDS_DiffCorrections_r12_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BDS_DiffCorrections_r12_1,
	2,	/* Elements count */
	&asn_SPC_BDS_DiffCorrections_r12_specs_1	/* Additional specs */
};

