/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_BDS_GridModelParameter_r12_H_
#define	_BDS_GridModelParameter_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "GridIonList-r12.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BDS-GridModelParameter-r12 */
typedef struct BDS_GridModelParameter_r12 {
	long	 bds_RefTime_r12;
	GridIonList_r12_t	 gridIonList_r12;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BDS_GridModelParameter_r12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BDS_GridModelParameter_r12;

#ifdef __cplusplus
}
#endif

#endif	/* _BDS_GridModelParameter_r12_H_ */
#include <asn_internal.h>
