/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#include "BDS-SgnTypeElement-r12.h"

static asn_TYPE_member_t asn_MBR_BDS_SgnTypeElement_r12_1[] = {
	{ ATF_POINTER, 1, offsetof(struct BDS_SgnTypeElement_r12, ganssSignalID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSSignalID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssSignalID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BDS_SgnTypeElement_r12, dbds_CorrectionList_r12),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DBDS_CorrectionList_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dbds-CorrectionList-r12"
		},
};
static const int asn_MAP_BDS_SgnTypeElement_r12_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_BDS_SgnTypeElement_r12_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BDS_SgnTypeElement_r12_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ganssSignalID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* dbds-CorrectionList-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_BDS_SgnTypeElement_r12_specs_1 = {
	sizeof(struct BDS_SgnTypeElement_r12),
	offsetof(struct BDS_SgnTypeElement_r12, _asn_ctx),
	asn_MAP_BDS_SgnTypeElement_r12_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_BDS_SgnTypeElement_r12_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BDS_SgnTypeElement_r12 = {
	"BDS-SgnTypeElement-r12",
	"BDS-SgnTypeElement-r12",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BDS_SgnTypeElement_r12_tags_1,
	sizeof(asn_DEF_BDS_SgnTypeElement_r12_tags_1)
		/sizeof(asn_DEF_BDS_SgnTypeElement_r12_tags_1[0]), /* 1 */
	asn_DEF_BDS_SgnTypeElement_r12_tags_1,	/* Same as above */
	sizeof(asn_DEF_BDS_SgnTypeElement_r12_tags_1)
		/sizeof(asn_DEF_BDS_SgnTypeElement_r12_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BDS_SgnTypeElement_r12_1,
	2,	/* Elements count */
	&asn_SPC_BDS_SgnTypeElement_r12_specs_1	/* Additional specs */
};

