/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_CNAVclockModel_H_
#define	_CNAVclockModel_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CNAVclockModel */
typedef struct CNAVclockModel {
	long	 cnavToc;
	long	 cnavTop;
	long	 cnavURA0;
	long	 cnavURA1;
	long	 cnavURA2;
	long	 cnavAf2;
	long	 cnavAf1;
	long	 cnavAf0;
	long	 cnavTgd;
	long	*cnavISCl1cp	/* OPTIONAL */;
	long	*cnavISCl1cd	/* OPTIONAL */;
	long	*cnavISCl1ca	/* OPTIONAL */;
	long	*cnavISCl2c	/* OPTIONAL */;
	long	*cnavISCl5i5	/* OPTIONAL */;
	long	*cnavISCl5q5	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CNAVclockModel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CNAVclockModel;

#ifdef __cplusplus
}
#endif

#endif	/* _CNAVclockModel_H_ */
#include <asn_internal.h>
