/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_DBDS_CorrectionElement_r12_H_
#define	_DBDS_CorrectionElement_r12_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SVID.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DBDS-CorrectionElement-r12 */
typedef struct DBDS_CorrectionElement_r12 {
	SVID_t	 svID;
	long	 bds_UDREI_r12;
	long	 bds_RURAI_r12;
	long	 bds_ECC_DeltaT_r12;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DBDS_CorrectionElement_r12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DBDS_CorrectionElement_r12;

#ifdef __cplusplus
}
#endif

#endif	/* _DBDS_CorrectionElement_r12_H_ */
#include <asn_internal.h>
