/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GANSSAssistance_H_
#define	_GANSSAssistance_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GANSSAssistance {
	GANSSAssistance_realTimeIntegrity	= 0,
	GANSSAssistance_differentialCorrections	= 1,
	GANSSAssistance_almanac	= 2,
	GANSSAssistance_referenceMeasurementInformation	= 3,
	GANSSAssistance_navigationModel	= 4,
	GANSSAssistance_timeModelGNSS_UTC	= 5,
	GANSSAssistance_timeModelGNSS_GNSS	= 6,
	GANSSAssistance_databitassistance	= 7,
	GANSSAssistance_ephemerisExtension	= 8,
	GANSSAssistance_ephemerisExtensionCheck	= 9,
	GANSSAssistance_addUTCmodel	= 10,
	GANSSAssistance_auxiliaryInformation	= 11,
	GANSSAssistance_gANSSRefMeasurementAssist_R12_Ext	= 12,
	GANSSAssistance_bdsDifferentialCorrections_r12	= 13,
	GANSSAssistance_bdsGridModel_r12	= 14
} e_GANSSAssistance;

/* GANSSAssistance */
typedef BIT_STRING_t	 GANSSAssistance_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSAssistance;
asn_struct_free_f GANSSAssistance_free;
asn_struct_print_f GANSSAssistance_print;
asn_constr_check_f GANSSAssistance_constraint;
ber_type_decoder_f GANSSAssistance_decode_ber;
der_type_encoder_f GANSSAssistance_encode_der;
xer_type_decoder_f GANSSAssistance_decode_xer;
xer_type_encoder_f GANSSAssistance_encode_xer;
per_type_decoder_f GANSSAssistance_decode_uper;
per_type_encoder_f GANSSAssistance_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _GANSSAssistance_H_ */
#include <asn_internal.h>
