/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#include "GANSSGenericAssistDataElement.h"

static int
memb_ganssID_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sbasID_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 7)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ganssID_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sbasID_constr_14 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_GANSSGenericAssistDataElement_1[] = {
	{ ATF_POINTER, 22, offsetof(struct GANSSGenericAssistDataElement, ganssID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_ganssID_constraint_1,
		&asn_PER_memb_ganssID_constr_2,
		0,
		"ganssID"
		},
	{ ATF_POINTER, 21, offsetof(struct GANSSGenericAssistDataElement, ganssTimeModel),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeqOfGANSSTimeModel,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssTimeModel"
		},
	{ ATF_POINTER, 20, offsetof(struct GANSSGenericAssistDataElement, ganssDiffCorrections),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSDiffCorrections,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssDiffCorrections"
		},
	{ ATF_POINTER, 19, offsetof(struct GANSSGenericAssistDataElement, ganssNavigationModel),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSNavModel,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssNavigationModel"
		},
	{ ATF_POINTER, 18, offsetof(struct GANSSGenericAssistDataElement, ganssRealTimeIntegrity),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSRealTimeIntegrity,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssRealTimeIntegrity"
		},
	{ ATF_POINTER, 17, offsetof(struct GANSSGenericAssistDataElement, ganssDataBitAssist),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSDataBitAssist,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssDataBitAssist"
		},
	{ ATF_POINTER, 16, offsetof(struct GANSSGenericAssistDataElement, ganssRefMeasurementAssist),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSRefMeasurementAssist,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssRefMeasurementAssist"
		},
	{ ATF_POINTER, 15, offsetof(struct GANSSGenericAssistDataElement, ganssAlmanacModel),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSAlmanacModel,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssAlmanacModel"
		},
	{ ATF_POINTER, 14, offsetof(struct GANSSGenericAssistDataElement, ganssUTCModel),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSUTCModel,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssUTCModel"
		},
	{ ATF_POINTER, 13, offsetof(struct GANSSGenericAssistDataElement, ganssEphemerisExtension),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSEphemerisExtension,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssEphemerisExtension"
		},
	{ ATF_POINTER, 12, offsetof(struct GANSSGenericAssistDataElement, ganssEphemerisExtCheck),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSEphemerisExtensionCheck,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssEphemerisExtCheck"
		},
	{ ATF_POINTER, 11, offsetof(struct GANSSGenericAssistDataElement, sbasID),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_sbasID_constraint_1,
		&asn_PER_memb_sbasID_constr_14,
		0,
		"sbasID"
		},
	{ ATF_POINTER, 10, offsetof(struct GANSSGenericAssistDataElement, ganssAddUTCModel),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GANSSAddUTCModel,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssAddUTCModel"
		},
	{ ATF_POINTER, 9, offsetof(struct GANSSGenericAssistDataElement, ganssAuxiliaryInfo),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GANSSAuxiliaryInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssAuxiliaryInfo"
		},
	{ ATF_POINTER, 8, offsetof(struct GANSSGenericAssistDataElement, ganssDiffCorrectionsValidityPeriod),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSDiffCorrectionsValidityPeriod,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssDiffCorrectionsValidityPeriod"
		},
	{ ATF_POINTER, 7, offsetof(struct GANSSGenericAssistDataElement, ganssTimeModel_R10_Ext),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeqOfGANSSTimeModel_R10_Ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssTimeModel-R10-Ext"
		},
	{ ATF_POINTER, 6, offsetof(struct GANSSGenericAssistDataElement, ganssRefMeasurementAssist_R10_Ext),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSRefMeasurementAssist_R10_Ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssRefMeasurementAssist-R10-Ext"
		},
	{ ATF_POINTER, 5, offsetof(struct GANSSGenericAssistDataElement, ganssAlmanacModel_R10_Ext),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSAlmanacModel_R10_Ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssAlmanacModel-R10-Ext"
		},
	{ ATF_POINTER, 4, offsetof(struct GANSSGenericAssistDataElement, ganssAlmanacModel_R12_Ext),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSAlmanacModel_R12_Ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssAlmanacModel-R12-Ext"
		},
	{ ATF_POINTER, 3, offsetof(struct GANSSGenericAssistDataElement, ganssRefMeasurementAssist_R12_Ext),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSRefMeasurementAssist_R12_Ext,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssRefMeasurementAssist-R12-Ext"
		},
	{ ATF_POINTER, 2, offsetof(struct GANSSGenericAssistDataElement, bdsDifferentialCorrections_r12),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BDS_DiffCorrections_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"bdsDifferentialCorrections-r12"
		},
	{ ATF_POINTER, 1, offsetof(struct GANSSGenericAssistDataElement, bdsGridModel_r12),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BDS_GridModelParameter_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"bdsGridModel-r12"
		},
};
static const int asn_MAP_GANSSGenericAssistDataElement_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21 };
static const ber_tlv_tag_t asn_DEF_GANSSGenericAssistDataElement_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GANSSGenericAssistDataElement_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ganssID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ganssTimeModel */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ganssDiffCorrections */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ganssNavigationModel */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ganssRealTimeIntegrity */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ganssDataBitAssist */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ganssRefMeasurementAssist */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* ganssAlmanacModel */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* ganssUTCModel */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* ganssEphemerisExtension */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* ganssEphemerisExtCheck */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* sbasID */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* ganssAddUTCModel */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* ganssAuxiliaryInfo */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* ganssDiffCorrectionsValidityPeriod */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* ganssTimeModel-R10-Ext */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* ganssRefMeasurementAssist-R10-Ext */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* ganssAlmanacModel-R10-Ext */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* ganssAlmanacModel-R12-Ext */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* ganssRefMeasurementAssist-R12-Ext */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* bdsDifferentialCorrections-r12 */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 } /* bdsGridModel-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_GANSSGenericAssistDataElement_specs_1 = {
	sizeof(struct GANSSGenericAssistDataElement),
	offsetof(struct GANSSGenericAssistDataElement, _asn_ctx),
	asn_MAP_GANSSGenericAssistDataElement_tag2el_1,
	22,	/* Count of tags in the map */
	asn_MAP_GANSSGenericAssistDataElement_oms_1,	/* Optional members */
	11, 11,	/* Root/Additions */
	10,	/* Start extensions */
	23	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GANSSGenericAssistDataElement = {
	"GANSSGenericAssistDataElement",
	"GANSSGenericAssistDataElement",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GANSSGenericAssistDataElement_tags_1,
	sizeof(asn_DEF_GANSSGenericAssistDataElement_tags_1)
		/sizeof(asn_DEF_GANSSGenericAssistDataElement_tags_1[0]), /* 1 */
	asn_DEF_GANSSGenericAssistDataElement_tags_1,	/* Same as above */
	sizeof(asn_DEF_GANSSGenericAssistDataElement_tags_1)
		/sizeof(asn_DEF_GANSSGenericAssistDataElement_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GANSSGenericAssistDataElement_1,
	22,	/* Elements count */
	&asn_SPC_GANSSGenericAssistDataElement_specs_1	/* Additional specs */
};

