/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GANSSRefMeasurement_R12_Ext_Element_H_
#define	_GANSSRefMeasurement_R12_Ext_Element_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SVID.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum dopplerUncertaintyExt {
	dopplerUncertaintyExt_d60	= 0,
	dopplerUncertaintyExt_d80	= 1,
	dopplerUncertaintyExt_d100	= 2,
	dopplerUncertaintyExt_d120	= 3,
	dopplerUncertaintyExt_noInformation	= 4
	/*
	 * Enumeration is extensible
	 */
} e_dopplerUncertaintyExt;

/* GANSSRefMeasurement-R12-Ext-Element */
typedef struct GANSSRefMeasurement_R12_Ext_Element {
	SVID_t	 svID;
	long	 dopplerUncertaintyExt;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSRefMeasurement_R12_Ext_Element_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_dopplerUncertaintyExt_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_GANSSRefMeasurement_R12_Ext_Element;

#ifdef __cplusplus
}
#endif

#endif	/* _GANSSRefMeasurement_R12_Ext_Element_H_ */
#include <asn_internal.h>
