/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GANSS_MsrElement_H_
#define	_GANSS_MsrElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "SeqOfGANSS-SgnTypeElement.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GANSS-MsrElement */
typedef struct GANSS_MsrElement {
	long	*ganssID	/* OPTIONAL */;
	SeqOfGANSS_SgnTypeElement_t	 ganss_SgnTypeList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSS_MsrElement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSS_MsrElement;

#ifdef __cplusplus
}
#endif

#endif	/* _GANSS_MsrElement_H_ */
#include <asn_internal.h>
