/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GANSSAssistanceForOneGANSS_H_
#define	_GANSSAssistanceForOneGANSS_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "GANSSAssistance.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GANSSAssistanceForOneGANSS */
typedef struct GANSSAssistanceForOneGANSS {
	long	*ganssID	/* OPTIONAL */;
	GANSSAssistance_t	 gANSSAssistance;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSAssistanceForOneGANSS_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSAssistanceForOneGANSS;

#ifdef __cplusplus
}
#endif

#endif	/* _GANSSAssistanceForOneGANSS_H_ */
#include <asn_internal.h>
