/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#include "GANSS-SgnTypeElement.h"

static int
memb_ganssCodePhaseAmbiguity_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 127)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_ganssCodePhaseAmbiguity_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  127 }	/* (0..127) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_GANSS_SgnTypeElement_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GANSS_SgnTypeElement, ganssSignalID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSSignalID,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssSignalID"
		},
	{ ATF_POINTER, 1, offsetof(struct GANSS_SgnTypeElement, ganssCodePhaseAmbiguity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_ganssCodePhaseAmbiguity_constraint_1,
		&asn_PER_memb_ganssCodePhaseAmbiguity_constr_3,
		0,
		"ganssCodePhaseAmbiguity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GANSS_SgnTypeElement, ganss_SgnList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeqOfGANSS_SgnElement,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganss-SgnList"
		},
};
static const int asn_MAP_GANSS_SgnTypeElement_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_GANSS_SgnTypeElement_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GANSS_SgnTypeElement_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ganssSignalID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ganssCodePhaseAmbiguity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ganss-SgnList */
};
static asn_SEQUENCE_specifics_t asn_SPC_GANSS_SgnTypeElement_specs_1 = {
	sizeof(struct GANSS_SgnTypeElement),
	offsetof(struct GANSS_SgnTypeElement, _asn_ctx),
	asn_MAP_GANSS_SgnTypeElement_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_GANSS_SgnTypeElement_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GANSS_SgnTypeElement = {
	"GANSS-SgnTypeElement",
	"GANSS-SgnTypeElement",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GANSS_SgnTypeElement_tags_1,
	sizeof(asn_DEF_GANSS_SgnTypeElement_tags_1)
		/sizeof(asn_DEF_GANSS_SgnTypeElement_tags_1[0]), /* 1 */
	asn_DEF_GANSS_SgnTypeElement_tags_1,	/* Same as above */
	sizeof(asn_DEF_GANSS_SgnTypeElement_tags_1)
		/sizeof(asn_DEF_GANSS_SgnTypeElement_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GANSS_SgnTypeElement_1,
	3,	/* Elements count */
	&asn_SPC_GANSS_SgnTypeElement_specs_1	/* Additional specs */
};

