/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GANSSDeltaElementList_H_
#define	_GANSSDeltaElementList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GANSSDeltaElementList */
typedef struct GANSSDeltaElementList {
	A_SEQUENCE_OF(OCTET_STRING_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSDeltaElementList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSDeltaElementList;

#ifdef __cplusplus
}
#endif

#endif	/* _GANSSDeltaElementList_H_ */
#include <asn_internal.h>
