/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GANSSDiffCorrectionsValidityPeriod_H_
#define	_GANSSDiffCorrectionsValidityPeriod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DGANSSExtensionSgnTypeElement;

/* GANSSDiffCorrectionsValidityPeriod */
typedef struct GANSSDiffCorrectionsValidityPeriod {
	A_SEQUENCE_OF(struct DGANSSExtensionSgnTypeElement) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSDiffCorrectionsValidityPeriod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSDiffCorrectionsValidityPeriod;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DGANSSExtensionSgnTypeElement.h"

#endif	/* _GANSSDiffCorrectionsValidityPeriod_H_ */
#include <asn_internal.h>
