/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#include "GANSSEphemerisExtension.h"

static asn_TYPE_member_t asn_MBR_GANSSEphemerisExtension_1[] = {
	{ ATF_POINTER, 3, offsetof(struct GANSSEphemerisExtension, ganssEphemerisHeader),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSEphemerisExtensionHeader,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssEphemerisHeader"
		},
	{ ATF_POINTER, 2, offsetof(struct GANSSEphemerisExtension, ganssReferenceSet),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeqOfGANSSRefOrbit,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssReferenceSet"
		},
	{ ATF_POINTER, 1, offsetof(struct GANSSEphemerisExtension, ganssephemerisDeltasMatrix),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSEphemerisDeltaMatrix,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ganssephemerisDeltasMatrix"
		},
};
static const int asn_MAP_GANSSEphemerisExtension_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_GANSSEphemerisExtension_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GANSSEphemerisExtension_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ganssEphemerisHeader */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ganssReferenceSet */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ganssephemerisDeltasMatrix */
};
static asn_SEQUENCE_specifics_t asn_SPC_GANSSEphemerisExtension_specs_1 = {
	sizeof(struct GANSSEphemerisExtension),
	offsetof(struct GANSSEphemerisExtension, _asn_ctx),
	asn_MAP_GANSSEphemerisExtension_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_GANSSEphemerisExtension_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GANSSEphemerisExtension = {
	"GANSSEphemerisExtension",
	"GANSSEphemerisExtension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GANSSEphemerisExtension_tags_1,
	sizeof(asn_DEF_GANSSEphemerisExtension_tags_1)
		/sizeof(asn_DEF_GANSSEphemerisExtension_tags_1[0]), /* 1 */
	asn_DEF_GANSSEphemerisExtension_tags_1,	/* Same as above */
	sizeof(asn_DEF_GANSSEphemerisExtension_tags_1)
		/sizeof(asn_DEF_GANSSEphemerisExtension_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GANSSEphemerisExtension_1,
	3,	/* Elements count */
	&asn_SPC_GANSSEphemerisExtension_specs_1	/* Additional specs */
};

