/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GANSSRefMeasurementAssist_R12_Ext_H_
#define	_GANSSRefMeasurementAssist_R12_Ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GANSSSignalID.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SeqOfGANSSRefMeasurementElement_R12;

/* GANSSRefMeasurementAssist-R12-Ext */
typedef struct GANSSRefMeasurementAssist_R12_Ext {
	GANSSSignalID_t	 ganssSignalID;
	long	*confidence	/* OPTIONAL */;
	struct SeqOfGANSSRefMeasurementElement_R12	*ganssRefMeasAssistList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSRefMeasurementAssist_R12_Ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSRefMeasurementAssist_R12_Ext;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SeqOfGANSSRefMeasurementElement-R12.h"

#endif	/* _GANSSRefMeasurementAssist_R12_Ext_H_ */
#include <asn_internal.h>
