/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GANSSDataBitsSgnElement_H_
#define	_GANSSDataBitsSgnElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "GANSSSignalID.h"
#include "SeqOf-GANSSDataBits.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GANSSDataBitsSgnElement */
typedef struct GANSSDataBitsSgnElement {
	GANSSSignalID_t	 ganssSignalType;
	SeqOf_GANSSDataBits_t	 ganssDataBits;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSDataBitsSgnElement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSDataBitsSgnElement;

#ifdef __cplusplus
}
#endif

#endif	/* _GANSSDataBitsSgnElement_H_ */
#include <asn_internal.h>
