/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GANSSEphemerisExtensionTime_H_
#define	_GANSSEphemerisExtensionTime_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "GANSSTOD.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GANSSEphemerisExtensionTime */
typedef struct GANSSEphemerisExtensionTime {
	long	 ganssEphExtDay;
	GANSSTOD_t	 ganssEphExtTOD;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSSEphemerisExtensionTime_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSSEphemerisExtensionTime;

#ifdef __cplusplus
}
#endif

#endif	/* _GANSSEphemerisExtensionTime_H_ */
#include <asn_internal.h>
