/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#include "GANSSAlmanacElement.h"

static asn_per_constraints_t asn_PER_type_GANSSAlmanacElement_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_GANSSAlmanacElement_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GANSSAlmanacElement, choice.keplerianAlmanacSet),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Almanac_KeplerianSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"keplerianAlmanacSet"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GANSSAlmanacElement, choice.keplerianNAVAlmanac),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Almanac_NAVKeplerianSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"keplerianNAVAlmanac"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GANSSAlmanacElement, choice.keplerianReducedAlmanac),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Almanac_ReducedKeplerianSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"keplerianReducedAlmanac"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GANSSAlmanacElement, choice.keplerianMidiAlmanac),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Almanac_MidiAlmanacSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"keplerianMidiAlmanac"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GANSSAlmanacElement, choice.keplerianGLONASS),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Almanac_GlonassAlmanacSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"keplerianGLONASS"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GANSSAlmanacElement, choice.ecefSBASAlmanac),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Almanac_ECEFsbasAlmanacSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ecefSBASAlmanac"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GANSSAlmanacElement, choice.keplerianBDSAlmanac_r12),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Almanac_BDSAlmanacSet_r12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"keplerianBDSAlmanac-r12"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_GANSSAlmanacElement_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* keplerianAlmanacSet */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* keplerianNAVAlmanac */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* keplerianReducedAlmanac */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* keplerianMidiAlmanac */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* keplerianGLONASS */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ecefSBASAlmanac */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* keplerianBDSAlmanac-r12 */
};
static asn_CHOICE_specifics_t asn_SPC_GANSSAlmanacElement_specs_1 = {
	sizeof(struct GANSSAlmanacElement),
	offsetof(struct GANSSAlmanacElement, _asn_ctx),
	offsetof(struct GANSSAlmanacElement, present),
	sizeof(((struct GANSSAlmanacElement *)0)->present),
	asn_MAP_GANSSAlmanacElement_tag2el_1,
	7,	/* Count of tags in the map */
	0,
	1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_GANSSAlmanacElement = {
	"GANSSAlmanacElement",
	"GANSSAlmanacElement",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_GANSSAlmanacElement_constr_1,
	asn_MBR_GANSSAlmanacElement_1,
	7,	/* Elements count */
	&asn_SPC_GANSSAlmanacElement_specs_1	/* Additional specs */
};

