/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#include "GLONASSclockModel.h"

static int
memb_gloTau_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -2097152 && value <= 2097151)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_gloGamma_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -1024 && value <= 1023)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_gloDeltaTau_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -16 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_gloTau_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 22, -1, -2097152,  2097151 }	/* (-2097152..2097151) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_gloGamma_constr_3 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 11,  11, -1024,  1023 }	/* (-1024..1023) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_gloDeltaTau_constr_4 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5, -16,  15 }	/* (-16..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_GLONASSclockModel_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GLONASSclockModel, gloTau),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_gloTau_constraint_1,
		&asn_PER_memb_gloTau_constr_2,
		0,
		"gloTau"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GLONASSclockModel, gloGamma),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_gloGamma_constraint_1,
		&asn_PER_memb_gloGamma_constr_3,
		0,
		"gloGamma"
		},
	{ ATF_POINTER, 1, offsetof(struct GLONASSclockModel, gloDeltaTau),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_gloDeltaTau_constraint_1,
		&asn_PER_memb_gloDeltaTau_constr_4,
		0,
		"gloDeltaTau"
		},
};
static const int asn_MAP_GLONASSclockModel_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_GLONASSclockModel_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GLONASSclockModel_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gloTau */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gloGamma */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* gloDeltaTau */
};
static asn_SEQUENCE_specifics_t asn_SPC_GLONASSclockModel_specs_1 = {
	sizeof(struct GLONASSclockModel),
	offsetof(struct GLONASSclockModel, _asn_ctx),
	asn_MAP_GLONASSclockModel_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_GLONASSclockModel_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GLONASSclockModel = {
	"GLONASSclockModel",
	"GLONASSclockModel",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GLONASSclockModel_tags_1,
	sizeof(asn_DEF_GLONASSclockModel_tags_1)
		/sizeof(asn_DEF_GLONASSclockModel_tags_1[0]), /* 1 */
	asn_DEF_GLONASSclockModel_tags_1,	/* Same as above */
	sizeof(asn_DEF_GLONASSclockModel_tags_1)
		/sizeof(asn_DEF_GLONASSclockModel_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GLONASSclockModel_1,
	3,	/* Elements count */
	&asn_SPC_GLONASSclockModel_specs_1	/* Additional specs */
};

