/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GPSAcquisAssist_R12_Ext_H_
#define	_GPSAcquisAssist_R12_Ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SeqOfGPSAcquisAssist_R12_Ext;

/* GPSAcquisAssist-R12-Ext */
typedef struct GPSAcquisAssist_R12_Ext {
	long	*confidence	/* OPTIONAL */;
	struct SeqOfGPSAcquisAssist_R12_Ext	*acquisList	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GPSAcquisAssist_R12_Ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GPSAcquisAssist_R12_Ext;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SeqOfGPSAcquisAssist-R12-Ext.h"

#endif	/* _GPSAcquisAssist_R12_Ext_H_ */
#include <asn_internal.h>
