/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GPSAcquisAssist_R12_Ext_Element_H_
#define	_GPSAcquisAssist_R12_Ext_Element_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SatelliteID.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum dopplerUncertaintyExt2 {
	dopplerUncertaintyExt2_d300	= 0,
	dopplerUncertaintyExt2_d400	= 1,
	dopplerUncertaintyExt2_d500	= 2,
	dopplerUncertaintyExt2_d600	= 3,
	dopplerUncertaintyExt2_noInformation	= 4
	/*
	 * Enumeration is extensible
	 */
} e_dopplerUncertaintyExt2;

/* GPSAcquisAssist-R12-Ext-Element */
typedef struct GPSAcquisAssist_R12_Ext_Element {
	SatelliteID_t	 satelliteID;
	long	 dopplerUncertaintyExt2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GPSAcquisAssist_R12_Ext_Element_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_dopplerUncertaintyExt2_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_GPSAcquisAssist_R12_Ext_Element;

#ifdef __cplusplus
}
#endif

#endif	/* _GPSAcquisAssist_R12_Ext_Element_H_ */
#include <asn_internal.h>
