/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_GPSAcquisAssist_R10_Ext_H_
#define	_GPSAcquisAssist_R10_Ext_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GPSAcquisAssist_R10_Ext_Element;

/* GPSAcquisAssist-R10-Ext */
typedef struct GPSAcquisAssist_R10_Ext {
	A_SEQUENCE_OF(struct GPSAcquisAssist_R10_Ext_Element) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GPSAcquisAssist_R10_Ext_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GPSAcquisAssist_R10_Ext;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GPSAcquisAssist-R10-Ext-Element.h"

#endif	/* _GPSAcquisAssist_R10_Ext_H_ */
#include <asn_internal.h>
