/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#include "GPSEphemerisExtension.h"

static asn_TYPE_member_t asn_MBR_GPSEphemerisExtension_1[] = {
	{ ATF_POINTER, 3, offsetof(struct GPSEphemerisExtension, gpsEphemerisHeader),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GPSEphemerisExtensionHeader,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"gpsEphemerisHeader"
		},
	{ ATF_POINTER, 2, offsetof(struct GPSEphemerisExtension, gpsReferenceSet),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeqOfGPSRefOrbit,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"gpsReferenceSet"
		},
	{ ATF_POINTER, 1, offsetof(struct GPSEphemerisExtension, gpsephemerisDeltaMatrix),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GPSEphemerisDeltaMatrix,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"gpsephemerisDeltaMatrix"
		},
};
static const int asn_MAP_GPSEphemerisExtension_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_GPSEphemerisExtension_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GPSEphemerisExtension_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gpsEphemerisHeader */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gpsReferenceSet */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* gpsephemerisDeltaMatrix */
};
static asn_SEQUENCE_specifics_t asn_SPC_GPSEphemerisExtension_specs_1 = {
	sizeof(struct GPSEphemerisExtension),
	offsetof(struct GPSEphemerisExtension, _asn_ctx),
	asn_MAP_GPSEphemerisExtension_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_GPSEphemerisExtension_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	2,	/* Start extensions */
	4	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GPSEphemerisExtension = {
	"GPSEphemerisExtension",
	"GPSEphemerisExtension",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_GPSEphemerisExtension_tags_1,
	sizeof(asn_DEF_GPSEphemerisExtension_tags_1)
		/sizeof(asn_DEF_GPSEphemerisExtension_tags_1[0]), /* 1 */
	asn_DEF_GPSEphemerisExtension_tags_1,	/* Same as above */
	sizeof(asn_DEF_GPSEphemerisExtension_tags_1)
		/sizeof(asn_DEF_GPSEphemerisExtension_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_GPSEphemerisExtension_1,
	3,	/* Elements count */
	&asn_SPC_GPSEphemerisExtension_specs_1	/* Additional specs */
};

