/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SBASID_H_
#define	_SBASID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SBASID {
	SBASID_waas	= 0,
	SBASID_egnos	= 1,
	SBASID_masas	= 2,
	SBASID_gagan	= 3
} e_SBASID;

/* SBASID */
typedef BIT_STRING_t	 SBASID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBASID;
asn_struct_free_f SBASID_free;
asn_struct_print_f SBASID_print;
asn_constr_check_f SBASID_constraint;
ber_type_decoder_f SBASID_decode_ber;
der_type_encoder_f SBASID_encode_der;
xer_type_decoder_f SBASID_decode_xer;
xer_type_encoder_f SBASID_encode_xer;
per_type_decoder_f SBASID_decode_uper;
per_type_encoder_f SBASID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SBASID_H_ */
#include <asn_internal.h>
