/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SBASclockModel_H_
#define	_SBASclockModel_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SBASclockModel */
typedef struct SBASclockModel {
	long	 sbasTo;
	long	 sbasAgfo;
	long	 sbasAgf1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SBASclockModel_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SBASclockModel;

#ifdef __cplusplus
}
#endif

#endif	/* _SBASclockModel_H_ */
#include <asn_internal.h>
