/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SeqOfGANSSAlmanacElement_H_
#define	_SeqOfGANSSAlmanacElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GANSSAlmanacElement;

/* SeqOfGANSSAlmanacElement */
typedef struct SeqOfGANSSAlmanacElement {
	A_SEQUENCE_OF(struct GANSSAlmanacElement) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SeqOfGANSSAlmanacElement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeqOfGANSSAlmanacElement;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GANSSAlmanacElement.h"

#endif	/* _SeqOfGANSSAlmanacElement_H_ */
#include <asn_internal.h>
