/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 * 	`asn1c -gen-PER`
 */

#ifndef	_SeqOfGANSSRefMeasurementElement_R12_H_
#define	_SeqOfGANSSRefMeasurementElement_R12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GANSSRefMeasurement_R12_Ext_Element;

/* SeqOfGANSSRefMeasurementElement-R12 */
typedef struct SeqOfGANSSRefMeasurementElement_R12 {
	A_SEQUENCE_OF(struct GANSSRefMeasurement_R12_Ext_Element) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SeqOfGANSSRefMeasurementElement_R12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SeqOfGANSSRefMeasurementElement_R12;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GANSSRefMeasurement-R12-Ext-Element.h"

#endif	/* _SeqOfGANSSRefMeasurementElement_R12_H_ */
#include <asn_internal.h>
